server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/read_code?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
#指定外部logback配置文件，可以不需要，默认是resources下找
logging:
  config: classpath:logback.xml

open:
  code:
    token: p9XI3aAaWneW3TZsykp0OsfZ7DNey1BTZKSTza9M5WzfDETmuGn5UfPJaenEBIZUsvBn2ssGMC5f5jll+BDvYnQGS1k8ODVs0dmumFiDotRGQVxTk7Q7hCOB+3fKkS8m7qTiwi3Jd/QaLkFjEYU7hI0XL3yujqysUT5i5DFJcjGqJl6XCBiVde9rEyybsfOgUi5t2IIJSZCQB/rk+JBIncXgsI24PfXnXzE4irM75Ob2CNkKl/JXD86KX43nvVOyZjnZHR8ZxmZ5CuwWV2CjEKva5BTUH5bzFPo8SpD2omkq01GjQuyhtm/p98oPuZCaC3dl2LCEPMWBhEPrAEVozq/qhbOBPNtmIIaGYH8YrcW7veYSozaAHf82uOOPQ0IA5h/0+ECbH8g=
    param: 5d000008003700000000000000003d8888865474ae39530e8714741a51ef042c1c72178c740485350598d8d112a064e89ffadc37e1849a92d7c34b2b3991e18531108e08dfffdc2f8000391e911c6b763ab5f56e0be088c8d1d9